<?php
@session_start();

include("../commonfunctions.php");
include("Html2Text.php");
# Include the Autoloader (see "Libraries" for install instructions)
use Elasticsearch\ClientBuilder;
require '../vendor/autoload.php';
//use Html2Text\Html2Text;
$client = ClientBuilder::create()->build();
$searchParams['index'] = 'mongoindex1';
$searchParams['type']  = 'u_endata';

$concatstr="";


function encryptRJ256($string_to_encrypt)
{
	$key = "fPixAxOcDiGZFXeCCOfUF3SyGWCQQtuni/cx/yVvgCU="; //INSERT THE KEY GENERATED BY THE C# CLASS HERE
	$iv = "n8OspIyuqBHdTn0q/JRJfi9A9WZV61B8BqJQKxEw64E="; //INSERT THE IV GENERATED BY THE C# CLASS HERE
	$rtn = mcrypt_encrypt(MCRYPT_RIJNDAEL_256, $key, $string_to_encrypt, MCRYPT_MODE_CBC, $iv);
	$rtn = base64_encode($rtn);
	return($rtn);
}

function decryptRJ256($encrypted)
{
	$key = "fPixAxOcDiGZFXeCCOfUF3SyGWCQQtuni/cx/yVvgCU="; //INSERT THE KEY GENERATED BY THE C# CLASS HERE
	$iv = "n8OspIyuqBHdTn0q/JRJfi9A9WZV61B8BqJQKxEw64E="; //INSERT THE IV GENERATED BY THE C# CLASS HERE
    //PHP strips "+" and replaces with " ", but we need "+" so add it back in...
    $encrypted = str_replace(' ', '+', $encrypted);

    //get all the bits
    $key = base64_decode($key);
    $iv = base64_decode($iv);
    $encrypted = base64_decode($encrypted);

    $rtn = mcrypt_decrypt(MCRYPT_RIJNDAEL_256, $key, $encrypted, MCRYPT_MODE_CBC, $iv);
    $rtn = unpad($rtn);
    return($rtn);
}

//removes PKCS7 padding
function unpad($value)
{
    $blockSize = mcrypt_get_block_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_CBC);
    $packing = ord($value[strlen($value) - 1]);
    if($packing && $packing < $blockSize)
    {
        for($P = strlen($value) - 1; $P >= strlen($value) - $packing; $P--)
        {
            if(ord($value{$P}) != $packing)
            {
                $packing = 0;
            }
        }
    }

    return substr($value, 0, strlen($value) - $packing); 
}


if(isset($_REQUEST['streamolder']))
{
	$pavolder = $_REQUEST['lastrecordid']*40;
}
else
{
	$pavolder="0";
}

/* For analysing user behaviour in future*/
$analyticsquery = $conn->query("insert into searchquery set ownerid='".$_SESSION['ownerid']."',enduserid='".$_REQUEST['enduserid']."',dtype='".$_REQUEST['dtype']."',ddatasearch='".$_REQUEST['ddatasearch']."',musthave='".$_REQUEST['musthave']."',mustnothave='".$_REQUEST['mustnothave']."',fromda='".$_REQUEST['fromda']."',toda='".$_REQUEST['toda']."',ntinclude='".$_REQUEST['ntincludeimg']."',datesubmited='".date("Y-m-d H:i:s",time())."',ipaddress='".$_SERVER['REMOTE_ADDR']."'");

if(isset($_SESSION['ownerid']))
{
	$ownerg = $_SESSION['ownerid'];
	$concatstr .='{ "term" : { "endownerid" : "'.$ownerg.'" } } , { "term" : { "delete" : "1" } }'; 
}
if(isset($_REQUEST['enduserid']))
{	
	if($_REQUEST['enduserid']>'0')
	{
		$enduserid = $_REQUEST['enduserid'];
		$concatstr .=',{ "term" : { "enduserid" : "'.$enduserid.'" } }';
	}
}
if(isset($_REQUEST['dtype']))
{
	if(($_REQUEST['dtype']!='') || (strlen($_REQUEST['dtype'])>0))
	{
		
		if(($_REQUEST['dtype']!='5') && ($_REQUEST['dtype']!='11') && ($_REQUEST['dtype']!='12') && ($_REQUEST['dtype']!='13'))
		{
			$dtype = $_REQUEST['dtype'];
			$concatstr .=',{ "term" : { "dtype" : "'.$dtype.'" } }';
		}
		
		if($_REQUEST['dtype']=='13')
		{
			$dtype = $_REQUEST['dtype'];
			$concatstr .=',{ "term" : { "watchlist" : "1" } }';
		}
		if($_REQUEST['dtype']=='5')
		{
			$dtype = $_REQUEST['dtype'];
			$concatstr1.='"should" : [
              	{ "term" : { "dtype" : "6" } },{ "term" : { "dtype" : "5" } } 
              ],';
		}

	}
}

if($_REQUEST['musthave']!='')
{
	$concatstr .=', { 
								"bool": { 
									"should" : [ 
										{  "match" : { "decdata" : "'.$_REQUEST['musthave'].'" } }, {  "match" : { "app_title" : "'.$_REQUEST['musthave'].'" } }
											]
		}
	}';
}

if($_REQUEST["ntinclude"]=='1')
{
	$mustnothavestr .=', "must_not" : {  "term" : { "dtype" : "20" } }';
	$mustnothavestr .=', "must_not" : {  "term" : { "dtype" : "21" } }';
}

if($_REQUEST['mustnothave']!='')
{
	$mustnothavestr .=', "must_not" : {  "bool": { "should" : [ "match" : { "decdata" : "'.$_REQUEST['mustnothave'].'" } }, { "match" : { "app_title" :"'.$_REQUEST['mustnothave'].'" } } ] } } ';
}

if(($_REQUEST['fromda']!='') && ($_REQUEST['toda']!=''))
{
	if($_REQUEST['fromda']=='5')
	{
		$fromque = $conn->query("select jdt from U_endowners where sno='".$_SESSION['ownerid']."'");
		$fromquery = @$fromque->fetch_assoc();
		
		 $fromda = strtotime($fromquery['jdt'])*1000;
	}
	else 
	{
		$fromda = strtotime($_REQUEST['fromda'])*1000;
	}
	$toda = (strtotime($_REQUEST['toda'])+(23*3600))*1000;
	$rangeconcatstr .=',{ "range" : { "ddate" : { "gte" : '.$fromda.',  "lte" : '.$toda.' } } }';
}

if(isset($_REQUEST['ddatasearch']))
{
	$ddatasearch = strtolower($_REQUEST['ddatasearch']);
	/*if(($_REQUEST['dtype']!='') || (strlen($_REQUEST['dtype'])>0))
	{
		if($_REQUEST['dtype']!='11')
		{
			$checkdbquery = $conn->query("select * from searchin where id='".$_REQUEST['dtype']."'");
			$fetcharraydb = $checkdbquery->fetch_assoc();
			
			$ddataarray = explode($fetcharraydb['searchtxt'],$_REQUEST['ddatasearch']);
			$ddatasearch = trim($ddataarray[0]);
		}
		else {
			$ddatasearch = $_REQUEST['ddatasearch'];
		}
	}
	else {
		$ddatasearch = $_REQUEST['ddatasearch'];
	}*/
	/*if($_REQUEST["dtype"]=="11" || $_REQUEST["dtype"]=="")
	{
		
	}
	else if($_REQUEST['dtype']=='12')
	{
		if($ddatasearch!='')
		{
			$decdatastr ='"must" : { "match_phrase" : { "app_title" : "*'.$ddatasearch.'*" } } ,';
		}
		if($_REQUEST['ddatasearch']!='')
		{
			$highlight = ', "highlight": { 	"fields" : { "app_title" : {} } } ';
		}
	
	}
	else
	{
		if($ddatasearch!='')
		{
			$decdatastr ='"must" : { "wildcard" : { "decdata" : "*'.$ddatasearch.'*" } } ,';
		}
		if($_REQUEST['ddatasearch']!='')
		{
			$highlight = ', "highlight": { 	"fields" : { "decdata" : {} } } ';
		}
	}*/
	if($ddatasearch!="")
		{
			if($_REQUEST["searchtypes"]=="3" || $_REQUEST["searchtypes"]==3)
		   	{
		   		$rgconcat="";
		   	    $rg = (explode(" ",$ddatasearch));
		   	    $rgcount = count($rg);
		   	    if($rgcount>1)
		   	    {
		   	    	$rgconcat = '{
	   								"prefix" : 
	   								{ 
	   									"decdata" : "'.$ddatasearch.'" 
	   								}
  								},
  								{
	   								"prefix" : 
	   								{ 
	   									"app_title" : "'.$ddatasearch.'" 
	   								}
  								}';
			   	    for($i=0;$i<$rgcount;$i++)
			   	    {
			   	    	if($i==0)
			   	    	{
			   	    		$rgconcat.= ',{
			   								"prefix" : 
			   								{ 
			   									"decdata" : "'.$rg[$i].'" 
			   								}
		  								},
		  								{
			   								"prefix" : 
			   								{ 
			   									"app_title" : "'.$rg[$i].'" 
			   								}
		  								},';
			   	    	}
			   	    	else if($i==($rgcount-1))
			   	    	{
			   	    		$rgconcat.= '{
			   								"prefix" : 
			   								{ 
			   									"decdata" : "'.$rg[$i].'" 
			   								}
		  								},
		  								{
			   								"prefix" : 
			   								{ 
			   									"app_title" : "'.$rg[$i].'" 
			   								}
		  								}';
			   	    	}
			   	    	else
			   	    	{
			   	    		$rgconcat.= '{
			   								"prefix" : 
			   								{ 
			   									"decdata" : "'.$rg[$i].'" 
			   								}
		  								},
		  								{
			   								"prefix" : 
			   								{ 
			   									"app_title" : "'.$rg[$i].'" 
			   								}
		  								},';
			   	    	}
			   	    }
		   		}
		   		else
		   		{
		   			$rgconcat = '{
	   								"prefix" : 
	   								{ 
	   									"decdata" : "'.$ddatasearch.'" 
	   								}
  								},
  								{
	   								"prefix" : 
	   								{ 
	   									"app_title" : "'.$ddatasearch.'" 
	   								}
  								}';
		   		}
			   	//echo $rgconcat;
			   	$decdatastr = ' "must": [ { "bool": { "should" : [ '.$rgconcat.' ]
			   			}
			   		}
			   	],';
		   }
		   else if($_REQUEST["searchtypes"]=="2" || $_REQUEST["searchtypes"]==2)
		   {
		   		$decdatastr = ' "must": [ { "bool": { "should" : [ { "match_phrase_prefix" : {

		            "decdata": {

		                "query": "'.$ddatasearch.'",

		                "slop": 3,

		                "max_expansions": 10

		            }

		        } }, { "match_phrase_prefix" : {

		            "decdata": {

		                "query": "'.$ddatasearch.'",

		                "slop": 3,

		                "max_expansions": 10

		            }

		        } } ]
				   			}
				   		}
				   	],';
		   }
		   else
		   {
		   		$rgconcat="";
		   	    $rg = (explode(" ",$ddatasearch));
		   	    $rgcount = count($rg);
		   	    if($rgcount>1)
		   	    {

		   	    	$rgconcat = '{ "wildcard" : { "decdata" : "*'.$ddatasearch.'*" } }, { "wildcard" : { "app_title" : "*'.$ddatasearch.'*" } }';
			   	    for($i=0;$i<$rgcount;$i++)
			   	    {
			   	    	if($i==0)
			   	    	{
			   	    		$rgconcat.= ',{ "wildcard" : { "decdata" : "*'.$rg[$i].'*" } }, { "wildcard" : { "app_title" : "*'.$rg[$i].'*" } },';
			   	    	}
			   	    	else if($i==($rgcount-1))
			   	    	{
			   	    		$rgconcat.= '{ "wildcard" : { "decdata" : "*'.$rg[$i].'*" } }, { "wildcard" : { "app_title" : "*'.$rg[$i].'*" } }';
			   	    	}
			   	    	else
			   	    	{
			   	    		$rgconcat.= '{ "wildcard" : { "decdata" : "*'.$rg[$i].'*" } }, { "wildcard" : { "app_title" : "*'.$rg[$i].'*" } } ,';
			   	    	}
			   	    }
		   		}
		   		else
		   		{
		   			$rgconcat = '{ "wildcard" : { "decdata" : "*'.$ddatasearch.'*" } }, { "wildcard" : { "app_title" : "*'.$ddatasearch.'*" } }';
		   		}
			   	//echo $rgconcat;
			   	$decdatastr = ' "must": [ { "bool": { "should" : [ '.$rgconcat.' ]
			   			}
			   		}
			   	],';
		   }
		   
		   	/**/

		}
		else
		{
			//$decdatastr ='';
			
		}
		
	
}
$searchParams['body']= '{ 
	"from" : '.$pavolder.', 
		"size" : 40, 
		"sort" : [ { "ddate" : {"order" : "desc"}}, "_score" ], 
		"query" : { 
				"bool" : { 
							'.$decdatastr.'
							"filter" : { 
								"bool" : { '.$concatstr1.'
									"must" : [ '.$concatstr.' '.$rangeconcatstr.']'.$mustnothavestr.'
								} 
							} 
						
				}
		}'.$highlight.'		
} ';


$searchParams1['body']= '{ 

		"from" : '.$pavolder.', 
		"size" : 41, 
		"sort" : [ { "ddate" : {"order" : "desc"}}, "_score" ], 
		"query" : { 
				"bool" : { 
							'.$decdatastr.'
							"filter" : { 
								"bool" : { '.$concatstr1.'
									"must" : [ '.$concatstr.' '.$rangeconcatstr.']'.$mustnothavestr.'
								} 
							} 
						
				}
		}'.$highlight.'
} ';
/* $searchParams['body']= '{ 
		"from" : '.$pavolder.', 
		"size" : 40,
		 "sort" : [
        { "ddate" : {"order" : "desc"}},
        "_score"
    ],
		"query" : { 
			"bool" : { '.$decdatastr.'				"filter" : { 
					"bool" : { 
						"must" : [ '.$concatstr.' '.$rangeconcatstr.']'.$mustnothavestr.'
					} 
				} 
			} 
		} '.$highlight.'
		
}';


$searchParams1['body']= '{
		"from" : '.$pavolder.', 
		"size" : 40, 
		 "sort" : [
			{ "ddate" : {"order" : "desc"}},
			"_score"
		],
		"query" : { 
			"bool" : { 
				
						'.$decdatastr.'
						
				"filter" : { 
					"bool" : { 
						"must" : [ '.$concatstr.' '.$rangeconcatstr.']'.$mustnothavestr.'
					} 
				} 
			} 
		} '.$highlight.'
}';*/
/*if($_SERVER["REMOTE_ADDR"]=="1.23.117.93")
{
	  echo $searchParams["body"];
	 echo $searchParams1["body"];
}*/

$retDoc = $client->search($searchParams);

$retDoc1 = $client->search($searchParams1);

if($retDoc['hits']['total']>=1)
{
	$results=$retDoc['hits']['hits'];
}
if($retDoc1['hits']['total']>=1)
{
	$results1=$retDoc1['hits']['hits'];
}

$mincount = count($results);
$totalcount = count($results1);
if(isset($_SESSION['ownerid']) || (strlen($_SESSION['ownerid'])>0))
{
	if(isset($results))
	{
		foreach($results as $r)
		{
			
			$datefind = $r['_source']['ddate'];
			$lastaccess = ago($r['_source']['ddate']);
			$dtype = $r['_source']['dtype'];
			$watchlist = $r['_source']['watchlist'];
			$noteflag = $r['_source']['noteflag'];
			$note	= $r['_source']['note'];
			$apptitle = $r['_source']['app_title'];
			$watchlist = $r['_source']['watchlist'];
			if($lastaccess=='showdate')
			{
				$lastaccess=date("M d Y",$datefind)." at ".date("h:i",$datefind);
			}
			$day = date("d",$datefind);
			$month = date("M",$datefind);
			$year = date("Y",$datefind);
			
			
			$string_to_decrypt=$r['_source']['decdata'];
			
			$decdatalen =  strlen($r['_source']['decdata']);
			if($decdatalen>750)
			{
				$decdatastyle = "closemoreclass";
			}
				
			
			
			$dtypeque = $conn->query("select originaltxt from searchin where id='".$r['_source']['dtype']."'");
			$dtypequery = @$dtypeque->fetch_assoc();
			$queryima = $conn->query("select profilepic,name,designation,dept,groupid from U_endusers where sno='".$r['_source']['enduserid']."'");
			$queryimage = @$queryima->fetch_assoc();
			
			if(($_REQUEST['dtype']=='12') && ($_REQUEST['ddatasearch']!=''))
			{
				//$apptitle = str_replace(strtolower($apptitle),"<span class='highlight'>".strtolower($apptitle)." </span>",strtolower($apptitle));
				
				 
			}
			else if(($_REQUEST['dtype']!='12') && ($_REQUEST['ddatasearch']!=''))
			{
				
				//$string_to_decrypt = str_replace(strtolower($ddatasearch),"<span class='highlight'>".strtolower($ddatasearch)."</span>",strtolower($string_to_decrypt));
					
			}
			
			$json_user = $string_to_decrypt;
			$vtext = $json_user;
			//$vtext = new Html2Text($vtext);

			//$vtext =  $html2TextConverter->getText();
			if($dtype=='5')
			{
				$xmpstyle = "";
			}
			else
			{
				$xmpstyle = "word-wrap: normal;white-space: normal;";
			}
			?>
			<div class="divbox" id="endetect<?php echo $r['_source']['sno']; ?>" >
			<!-- Dropdown start -->
				<div class="dropdown" style="float:right;">
					<span class="caret glyphicon glyphicon-triangle-bottom" id="menu<?php echo $r['_source']['sno']; ?>" data-toggle="dropdown"></span>
					<ul class="dropdown-menu" role="menu" aria-labelledby="menu<?php echo $r['_source']['sno']; ?>">
						<?php if($watchlist=='1') { ?>
						<li role="presentation" id="addtowatchlist<?php echo $r['_source']['sno'];?>"><a role="menuitem" tabindex="-1"  onclick="watchlist('<?php echo $r['_source']['sno']; ?>','0')">Remove from watchlist</a></li>
						<?php }
						else
						{
						?>
						<li role="presentation" id="addtowatchlist<?php echo $r['_source']['sno'];?>"><a role="menuitem" tabindex="-1" onclick="watchlist('<?php echo $r['_source']['sno'];?>','1')">Add to watchlist</a></li>
						<?php } ?>
						<?php if($noteflag=='1') { ?>
						<li role="presentation" id="addtonotelist<?php echo $r['_source']['sno'];?>"><a role="menuitem" tabindex="-1"  onclick="addnote('<?php echo $r['_source']['sno']; ?>','0','<?php echo $note;?>')">Remove Note</a></li>
						<?php 
						}
						else
						{
						?>
						<li role="presentation" id="addtonotelist<?php echo $r['_source']['sno'];?>"><a role="menuitem" tabindex="-1" onclick="addnote('<?php echo $r['_source']['sno']; ?>','1','<?php echo $r['_source']['note'];?>')">Add Note</a></li>
						<?php 
						} 
						if($_REQUEST['enduserid']=="") 
						{
						?>
						<li role="presentation"><a role="menuitem" tabindex="-1" onclick="edituser('<?php echo $r['_source']['enduserid'];?>','<?php echo $queryimage['name'];?>','<?php echo $queryimage['dept'];?>','<?php echo $queryimage['designation'];?>','<?php echo $queryimage['groupid'];?>')">Edit User</a></li>
						<?php } ?>
				  	<li role="presentation"><a role="menuitem" tabindex="-1"  onclick="deletefromlist('<?php echo $r['_source']['sno']; ?>')">Delete</a></li>
				  	
					</ul>
				</div>
				<div id="note<?php echo $r['_source']['sno']?>" style="float:right;margin-right: 5px;margin-top: 11px;cursor:pointer;">
					<?php if($noteflag=='1') { ?>
					<span class="glyphicon glyphicon-list-alt"  onclick="shownote('<?php echo $r['_source']['sno']?>')"></span>
					<?php } ?>
				</div>
				<div id="watchlistimg<?php echo $r['_source']['sno']?>" style="float:right;">
				  <?php if($watchlist=='1') { ?>
				  <img src="images/watchlist.png">
				 <?php } ?>
				</div>
				<div id="stbody6" class="stbody">
					<?php if($_REQUEST["enduserid"]=="") { ?> 
					<div class="stimg">
						<div class="divboximage">
							<a href="userprofile.php?enduserid=<?php echo $r['_source']['enduserid'];?>"><img src="<?php echo $queryimage['profilepic'];?>" class="home_profile_pic"></a>
						</div>
					</div>
					<?php } ?>
					<?php 
						if($_REQUEST["enduserid"]!="") { 
							$style="margin-left:2px;";
						}
						if(isset($_REQUEST['enduserid']))
						{

							?>
								<div class="sttext1" style='<?php echo $style; ?>'>
							<?php   
						}
						else
						{
							?>
								<div class="sttext" style='<?php echo $style; ?>'>
							<?php 
						}
					?>
									<a id="6" class="stdelete" title="Delete update" href="#"> </a>
									
										<div class="divboxname" style="float:left">
											<?php if($_REQUEST["enduserid"]=="") { ?> 
											<b>
												<a href="userprofile.php?eid=<?php echo base64_encode($r['_source']['enduserid']);?>" style="float:left;">
													<?php echo $queryimage['name']; ?>
												</a>
											</b>
											<?php } else { ?> <div style="float:left"><?php echo $apptitle;?></div> <?php } ?>
											<div class="prevnextsearch glyphicon glyphicon-search" onclick="showprevnext('<?php echo $r['_source']['sno']; ?>','<?php echo $r['_source']['enduserid']?>')" id="movefocus<?php echo $r['_source']['sno']; ?>" style="float:left;"></div>
											&nbsp;&nbsp;&nbsp;
										</div>
									<br>
									<div style="clear:both;"></div>
									<div class="sttime" style="margin-top:5px;">
										<div style="float:left;"><?php echo $lastaccess;?></div><div style="float:left;margin-left:10px;"><i style="color: rgb(240, 101, 60);"><?php echo $dtypequery['originaltxt']; ?></i></div>
									</div>
									<div style="clear:both;"></div>
									<?php if($_REQUEST["enduserid"]=="") { ?>
									<div style="color:#3C5C9E;">
									<i>
										<div style="float:left;"><?php echo $apptitle;?></div>
									</i>
									</div>	
									<?php } ?>								
									<div style="clear:both;"></div>
									<div id="shownoteheader<?php echo $r['_source']['sno']?>" class="note yellow pin" style="display:none;margin-top:-50px;">
										<span class="glyphicon glyphicon-remove" style="float:right;color:#757575;margin-top:-10px;padding: 2px;cursor:pointer;" onclick="closenote('<?php echo $r['_source']['sno']?>')"></span> &nbsp;<span class="glyphicon glyphicon-pencil" style="float:right;color:#757575;margin-top:-10px;padding: 2px;cursor:pointer;" onclick="addnote('<?php echo $r['_source']['sno']?>','1','<?php echo $r['_source']['note']?>')"></span>
										<input type="hidden" name="editnote<?php echo $r['_source']['sno']?>" id="editnote<?php echo $r['_source']['sno']?>" value="<?php echo $r['_source']['note']?>">
										<div id="shownote<?php echo $r['_source']['sno']?>" style="float:left;">
										<?php 
								   			if($noteflag=='1')
								   			{	
								   				echo $r['_source']['note'];
											}
										?>
										</div>
									</div>
									<div id="stexpandbox<?php echo $r['_source']['sno'];?>" >
										<div id="stexpand6">
											<div class="divboxdata">
												<?php if(($dtype=='20') || ($dtype=='21')) { 
													$imageDataEncoded = $r['_source']['decdata'];
													?>
													<div style="margin-top:10px;">
													<?php if($_REQUEST["enduserid"]!="") { ?>
														<img style="cursor:pointer;border:1px solid #ccc;padding:3px;" src="thumbnail.php?src=<?php echo $imageDataEncoded; ?>&w=200&h=113"  onclick="popupusergallery('popUpDivgallery','<?php echo $imageDataEncoded; ?>','<?php echo $dtype; ?>','<?php echo mysqli_escape_string($r['_source']['app_title']); ?>','<?php echo $r['_source']['sno']?>','<?php echo $r['_source']['enduserid']; ?>','<?php echo $queryimage['name']; ?>','<?php echo $queryimage['designation'] ?>')"/>
													<?php
														} else {
															?>
															<img style="cursor:pointer;border:1px solid #ccc;padding:3px;" src="thumbnail.php?src=<?php echo $imageDataEncoded; ?>&w=200&h=113"  onclick="popupgallery('popUpDivgallery','<?php echo $watchlist; ?>', '<?php echo $imageDataEncoded; ?>','<?php echo $dtype; ?>','<?php echo mysqli_escape_string($r['_source']['app_title']); ?>','<?php echo $r['_source']['sno']?>','<?php echo $r['_source']['enduserid']; ?>','<?php echo $queryimage['name']; ?>','<?php echo $queryimage['designation'] ?>')"/>
															<?php
														}
													?>
													</div>
													<?php
													} 
													else 
													{
														?>
														<div id="divexpandbox<?php echo $r['_source']['sno']; ?>"  style="margin-top:10px;" class="<?php echo $decdatastyle;?>"><xmp><?php echo $vtext;?></xmp></div>
														<?php
													}							
												?>
											</div>
										</div>
										<?php if($decdatalen>750)
										{
										?>
										<div style="float:right;color: #3B5998;cursor: pointer;text-decoration: none;" id="readmorediv<?php echo $r['_source']['sno'];?>" onclick="readmorediv('divexpandbox<?php echo $r['_source']['sno'];?>','readmorediv<?php echo $r['_source']['sno'];?>','closemorediv<?php echo $r['_source']['sno'];?>')">See More</div><div style="display:none" id="closemorediv<?php echo $r['_source']['sno'];?>" onclick="closereadmore('divexpandbox<?php echo $r['_source']['sno'];?>','readmorediv<?php echo $r['_source']['sno'];?>','closemorediv<?php echo $r['_source']['sno'];?>')">Close</div>
										<?php 
										} 
										?>
									</div>
								</div>
				</div>
			</div>
		<?php
		}
	}
	if($totalcount>20)
	{
	?>
	<div class="panel-heading" onclick="loadmorestream(this)" id="loadmore<?php echo $r['_source']['sno'] ?>">
		<a ng-hide="ascrec">
			<h4 class="panel-title">
				<center style="cursor: pointer;">.. load more ..</center>
			</h4>
		</a>
	</div>
	<?php 
	}
	if($mincount=='0')
	{
		?>
	<div class="panel-heading">
		<a ng-hide="ascrec">
			<h4 class="panel-title">
				<center style="cursor: pointer;">No Records Found</center>
			</h4>
		</a>
	</div>
	<?php 
	}	
}
else 
{	
	echo "login";
}	
	$conn->close();
?>

